/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASK1_H_RPCGEN
#define _ASK1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputpair {
	int choice;
	float r;
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct inputpair inputpair;

struct output_avg {
	struct {
		u_int avg_len;
		float *avg_val;
	} avg;
};
typedef struct output_avg output_avg;

struct output_prod_r {
	struct {
		u_int arr_len;
		float *arr_val;
	} arr;
};
typedef struct output_prod_r output_prod_r;

#define OP_PROG 0x23451111
#define OP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IN_PROD 1
extern  int * in_prod_1(inputpair *, CLIENT *);
extern  int * in_prod_1_svc(inputpair *, struct svc_req *);
#define AVG 2
extern  output_avg * avg_1(inputpair *, CLIENT *);
extern  output_avg * avg_1_svc(inputpair *, struct svc_req *);
#define PROD_R 3
extern  output_prod_r * prod_r_1(inputpair *, CLIENT *);
extern  output_prod_r * prod_r_1_svc(inputpair *, struct svc_req *);
extern int op_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IN_PROD 1
extern  int * in_prod_1();
extern  int * in_prod_1_svc();
#define AVG 2
extern  output_avg * avg_1();
extern  output_avg * avg_1_svc();
#define PROD_R 3
extern  output_prod_r * prod_r_1();
extern  output_prod_r * prod_r_1_svc();
extern int op_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputpair (XDR *, inputpair*);
extern  bool_t xdr_output_avg (XDR *, output_avg*);
extern  bool_t xdr_output_prod_r (XDR *, output_prod_r*);

#else /* K&R C */
extern bool_t xdr_inputpair ();
extern bool_t xdr_output_avg ();
extern bool_t xdr_output_prod_r ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASK1_H_RPCGEN */
