/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask1.h"

bool_t
xdr_inputpair (XDR *xdrs, inputpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->choice))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->r))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_avg (XDR *xdrs, output_avg *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->avg.avg_val, (u_int *) &objp->avg.avg_len, 2,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_prod_r (XDR *xdrs, output_prod_r *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->arr.arr_val, (u_int *) &objp->arr.arr_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
